language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test --features ext,fun --all
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo bench --features ext,fun --all
      cargo bench --features ext,fun,quickcheck --all
    fi
