[package]
name = "fera-graphs"
version = "0.1.0"
authors = ["Marco A L Barbosa <malbarbo@gmail.com>"]

[features]
default = ["unstable"]
unstable = []

[dependencies]
rand = "0.3"
fera = { path = "../fera/" }
