[package]
name = "fera"
version = "0.1.0"
authors = ["Marco A L Barbosa <malbarbo@gmail.com>"]

[workspace]
members = [
    "ext",
    "fun",
    "graph",
    "optional",
    "unionfind",
]

[dependencies]
fera-ext = { path = "ext/", optional = true }
fera-fun = { path = "fun/", optional = true }
fera-graph = { path = "graph/", optional = true }
fera-optional = { path = "optional/", optional = true }
fera-unionfind = { path = "unionfind/", optional = true }

[features]
ext = ["fera-ext"]
fun = ["fera-fun"]
graph = ["fera-graph"]
optional = ["fera-optional"]
unionfind = ["fera-unionfind"]
