[package]
name = "fera-graphs"
version = "0.1.0"
authors = ["Marco A L Barbosa <malbarbo@gmail.com>"]

[features]
default = []
nightly = []
clippy = []

[dependencies]
num = "0.1"
num-traits = "0.1"
ordered-float = "0.3"
rand = "0.3"
fera = { path = "../fera/" }

[dev-dependencies]
itertools = "0.5"
quickcheck = "0.4"
