[package]
name = "fera-graph"
version = "0.1.0"
authors = ["Marco A L Barbosa <malbarbo@gmail.com>"]

[dependencies]
num-traits = "0.1"
rand = "0.3"
fnv = "1.0"
fera-fun = { path = "../fun/" }
fera-optional = { path = "../optional/" }
fera-unionfind = { path = "../unionfind/" }
quickcheck = { version = "0.4", optional = true }

[dev-dependencies]
itertools = "0.5"
