[package]
name = "fera-graph"
version = "0.1.0"
authors = ["malbarbo"]
description = """
Graph data structures and algorithms.
"""
repository = "https://github.com/malbarbo/fera/tree/master/graph"
readme = "README.md"
license = "MPL-2.0"

[dependencies]
num-traits = "0.1"
rand = "0.3"
fera-fun = { path = "../fun/" }
fera-optional = { path = "../optional/" }
fera-unionfind = { path = "../unionfind/" }
quickcheck = { version = "0.4.1", optional = true }

[dev-dependencies]
itertools = "0.7"
version-sync = "0.4"
